services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: python app.py

  frontend:
    # Use a simple web server to host the static frontend
    image: httpd:2.4-alpine
    ports:
      - "8080:80"
    volumes:
      # Mount the frontend folder into the server's web root
      - ./frontend:/usr/local/apache2/htdocs/