services:
  backend:
    build: ./backend
    container_name: pneumonia-backend
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: pneumonia-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped